name: Auto-Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release name of main repository'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - block
          - bookmark
          - clap
          - favorite
          - follow
          - like
          - rate
          - subscribe
          - support
          - visit
          - vote

    name: Release ${{ matrix.package }}

    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.name }}
          release_name: ${{ github.event.inputs.name }}
          commitish: ${{ github.ref }}
          repo: ${{ matrix.package }}
          body: "Release notes: [${{ github.event.inputs.name }}](https://github.com/laravel-interaction/interactions/releases/tag/${{ github.event.inputs.name }})"
